CONN SYS/SYS AS SYSDBA

GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO SALES;

CONN SALES/SALESMSH

CREATE DATABASE LINK PROS CONNECT TO SALES IDENTIFIED BY SALESMSH USING 'SERVER';

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC ADD_TABLES.ALTER_TABLES;

EXEC ADD_TABLES.ADD_ROW_NO;

EXEC ADD_TABLES.ADD_INSERT_DATE;

EXEC ADD_TABLES.CREATE_PROCEDURES_PACKAGE('O$%');

EXEC FAWZY$PROCEDURES;

EXEC ADD_TABLES.CREATE_PROCEDURES_PACKAGE('E$%');

EXEC FAWZY$PROCEDURES;

EXEC PACKETS.REMOVE_L$_E$_M$_O$_Q$;

CONN SYS/SYS AS SYSDBA

EXEC CREATE_DROP_USER('AUD_SALES','SALESMSH');

EXEC CREATE_DROP_USER('STRG_SALES','SALESMSH');

EXEC CREATE_DROP_USER('PROS_SALES','SALESMSH');

GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO AUD_SALES;
GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO STRG_SALES;
GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO PROS_SALES;

CONN AUD_SALES/SALESMSH

CREATE DATABASE LINK PROS CONNECT TO SALES IDENTIFIED BY SALESMSH USING 'SERVER';

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO STRG_SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PROS_SALES;

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC PACKETS.CREATE_DB_LINK('SALES','SALES','SALESMSH','SERVER'); 

EXEC PACKETS.CREATE_DB_LINK('STRG_SALES','STRG_SALES','SALESMSH','SERVER');

EXEC ADD_TABLES.ADD_DELETE_UPDATE_TABS_COLS('SALES');

EXEC ADD_TABLES.ALTER_SEQ;

EXEC ADD_TABLES.ADD_SEQ;

EXEC ADD_TABLES.CREATE_PROCEDURES_PACKAGE('O$%');

EXEC FAWZY$PROCEDURES;

EXEC PACKETS.REMOVE_L$_E$_M$_O$_Q$;

EXEC PACKETS.UPDATE_SEQ;

EXEC PACKETS.SEQ_TRIGGERS;

CONN SALES/SALESMSH

EXEC PACKETS.INSERT_TRIGGERS('AUD_SALES');

EXEC PACKETS.UPDATE_TRIGGERS('AUD_SALES');

EXEC PACKETS.DELETE_TRIGGERS('AUD_SALES');

EXEC PACKETS.UPDATE_ROW_NO;

EXEC PACKETS.ROW_NO_TRIGGERS;

CONN SYS/SYS AS SYSDBA

CONN STRG_SALES/SALESMSH

CREATE DATABASE LINK PROS CONNECT TO SALES IDENTIFIED BY SALESMSH USING 'SERVER';

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO AUD_SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PROS_SALES;

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC PACKETS.CREATE_DB_LINK('SALES','SALES','SALESMSH','SERVER');

EXEC ADD_TABLES.ADD_DELETE_UPDATE_TABS_COLS('SALES');

EXEC ADD_TABLES.ALTER_SEQ;

EXEC ADD_TABLES.ADD_SEQ;

EXEC ADD_TABLES.DROP_COLUMN_CONSTRAINTS('SEQ');

CONN PROS_SALES/SALESMSH

CREATE DATABASE LINK PROS CONNECT TO SALES IDENTIFIED BY SALESMSH USING 'SERVER';

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO STRG_SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO AUD_SALES;

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC PACKETS.CREATE_DB_LINK('SALES','SALES','SALESMSH','REP');

EXEC PACKETS.DELETE_UPDATE_INSERT_PROCEDURE('SALES','AUD_SALES');

EXEC PACKETS.PACKET_JOBS('10');

CONN SALES/SALESMSH

EXEC PACKETS.ADD_UPDATE_DATE_COLUMN

HOST

EXP SALES/SALESMSH@SERVER     FILE=C:\SALES_THIS_DAY.DMP
EXP AUD_SALES/SALESMSH@SERVER FILE=C:\AUD_SALES_THIS_DAY.DMP

IMP SALES/SALESMSH@REPLICAT     FULL=Y FILE=C:\SALES_THIS_DAY.DMP 
IMP AUD_SALES/SALESMSH@REPLICAT FULL=Y FILE=C:\AUD_SALES_THIS_DAY.DMP 

EXIT

CONN SALES/SALESMSH@REPLICAT

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO AUD_SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PROS_SALES;

CONN AUD_SALES/SALESMSH@REPLICAT

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO SALES;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PROS_SALES;

CONN PROS_SALES/SALESMSH@REPLICAT

CREATE DATABASE LINK PROS CONNECT TO SALES IDENTIFIED BY SALESMSH USING 'SERVER';

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC PACKETS.CREATE_DB_LINK('SALES','SALES','SALESMSH','REP');

EXEC PACKETS.DELETE_UPDATE_INSERT_PROCEDURE('SALES','AUD_SALES');

EXEC PACKETS.PACKET_JOBS('10');
