CONN SYSTEM/MANAGER@BON  

GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO PAYMAT;

CONN PAYMAT/PAYMSH@BON

CREATE DATABASE LINK PROS CONNECT TO PAYMAT IDENTIFIED BY PAYMSH USING 'SERVER';

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC ADD_TABLES.ALTER_TABLES;

EXEC ADD_TABLES.ADD_ROW_NO;

EXEC ADD_TABLES.ADD_INSERT_DATE;

EXEC ADD_TABLES.CREATE_PROCEDURES_PACKAGE('O$%');

EXEC FAWZY$PROCEDURES;

EXEC ADD_TABLES.CREATE_PROCEDURES_PACKAGE('E$%');

EXEC FAWZY$PROCEDURES;

EXEC PACKETS.REMOVE_L$_E$_M$_O$_Q$;

CONN SYSTEM/MANAGER@BON  

EXEC CREATE_USER('AUD_PAYMAT','PAYMAT');

EXEC CREATE_USER('STRG_PAYMAT','PAYMAT');

EXEC CREATE_USER('PROS_PAYMAT','PAYMAT');

GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO AUD_PAYMAT;
GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO STRG_PAYMAT;
GRANT CREATE TABLE , CREATE PROCEDURE , CREATE VIEW , CREATE TRIGGER ,CREATE DATABASE LINK TO PROS_PAYMAT;

CONN AUD_PAYMAT/PAYMSH@BON

CREATE DATABASE LINK PROS CONNECT TO PAYMAT IDENTIFIED BY PAYMSH USING 'SERVER';

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PAYMAT;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO STRG_PAYMAT;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PROS_PAYMAT;

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC PACKETS.CREATE_DB_LINK('PAYMAT','PAYMAT','PAYMSH','SERVER'); 

EXEC PACKETS.CREATE_DB_LINK('STRG_PAYMAT','STRG_PAYMAT','PAYMAT','SERVER');

EXEC ADD_TABLES.ADD_DELETE_UPDATE_TABS_COLS('PAYMAT');

EXEC ADD_TABLES.ALTER_SEQ_NO;

EXEC ADD_TABLES.ADD_SEQ_NO;

EXEC ADD_TABLES.CREATE_PROCEDURES_PACKAGE('O$%');

EXEC FAWZY$PROCEDURES;

EXEC PACKETS.REMOVE_L$_E$_M$_O$_Q$;

EXEC PACKETS.UPDATE_SEQ_NO;

EXEC PACKETS.SEQ_NO_TRIGGERS;

CONN PAYMAT/PAYMSH@BON

EXEC PACKETS.INSERT_TRIGGERS_TEST('AUD_PAYMAT');

EXEC PACKETS.INSERT_TRIGGERS('AUD_PAYMAT');

EXEC PACKETS.UPDATE_TRIGGERS('AUD_PAYMAT');

EXEC PACKETS.DELETE_TRIGGERS('AUD_PAYMAT');

EXEC PACKETS.UPDATE_ROW_NO;

EXEC PACKETS.ROW_NO_TRIGGERS;

CONN SYSTEM/MANAGER@BON  

CONN STRG_PAYMAT/PAYMSH@BON

CREATE DATABASE LINK PROS CONNECT TO PAYMAT IDENTIFIED BY PAYMSH USING 'SERVER';

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PAYMAT;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO AUD_PAYMAT;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PROS_PAYMAT;

@C:\PACKETS\PACKETS.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

EXEC PACKETS.CREATE_DB_LINK('PAYMAT','PAYMAT','PAYMAT','SERVER');

EXEC ADD_TABLES.ADD_DELETE_UPDATE_TABS_COLS('PAYMAT');

EXEC ADD_TABLES.ALTER_SEQ_NO;

EXEC ADD_TABLES.ADD_SEQ_NO;

EXEC ADD_TABLES.DROP_COLUMN_CONSTRAINTS('SEQ_NO');

CONN PROS_PAYMAT/PAYMSH@BON

CREATE DATABASE LINK PROS CONNECT TO RECEIVING IDENTIFIED BY RECEIVING USING 'SERVER';

GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO PAYMAT;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO STRG_PAYMAT;
GRANT SELECT ANY TABLE , INSERT ANY TABLE , UPDATE ANY TABLE , DELETE ANY TABLE TO AUD_PAYMAT;

--@C:\PACKETS\PACKETS.SQL
@C:\PACKETS\PACKETS_test_pros.SQL

EXEC PACKETS.CREATE_CURRENT_TABLES

@C:\PACKETS\ADD_TABLES.SQL

EXEC ADD_TABLES.INSERT_DEFAULT_TABLES;

--EXEC PACKETS.CREATE_DB_LINK('PAYMAT','PAYMAT','PAYMAT','REP');
EXEC PACKETS.CREATE_DB_LINK('HH','HH','HH','SERVER');

EXEC PACKETS.CREATE_DB_LINK('MANAGER','PAYMAT','PAYMAT','MANAGEMENT');

--EXEC PACKETS.DELETE_UPDATE_INSERT_PROCEDURE('PAYMAT','AUD_PAYMAT');
--EXEC PACKETS.DELETE_UPDATE_INSERT_PROCEDURE('HH','AUD_PAYMAT');
EXEC PACKETS.DELETE_UPDATE_INSERT_PROCEDURE('HH','PAYMAT','AUD_PAYMAT');

EXEC PACKETS.DELETE_UPDATE_INSERT_PROCEDURE('MANAGER','PAYMAT','AUD_PAYMAT');

EXEC PACKETS.PACKET_JOBS('10');

EXEC PACKETS.PACKET_JOBS_TH2('10');

CONN PAYMAT/PAYMSH@BON@MANAGEMENT

EXEC PACKETS.ADD_UPDATE_DATE_COLUMN

EXEC ADD_TABLES.DROP_COLUMN_CONSTRAINTS('ROW_NO');
